import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';

const tools = [
  {
    to: '/validate-idea',
    label: 'Validate Idea',
    desc: 'Market size, timing, and viability analysis for your startup concept.',
    tag: 'Step 1',
  },
  {
    to: '/generate-plan',
    label: 'Business Plan',
    desc: 'Structured plan with market analysis, competitive landscape, and strategy.',
    tag: 'Step 2',
  },
  {
    to: '/business-model',
    label: 'Business Model',
    desc: 'Lean canvas covering value proposition, channels, and revenue streams.',
    tag: 'Step 3',
  },
  {
    to: '/pitch-deck',
    label: 'Pitch Deck',
    desc: 'Ten investor-ready slides from problem to ask, generated by the LLM pipeline.',
    tag: 'Step 4',
  },
];

export default function DashboardPage() {
  const { user } = useAuth();

  return (
    <div style={{ padding: '64px 0 80px' }} className="fade-in">
      <div className="page">

        {/* Header */}
        <div style={{ marginBottom: 56 }}>
          <p className="label" style={{ marginBottom: 12 }}>Dashboard</p>
          <h1 style={{
            fontSize: '1.75rem',
            fontWeight: 500,
            letterSpacing: '-0.03em',
            color: 'var(--text-primary)',
            marginBottom: 10,
          }}>
            {user?.name ? `Good to see you, ${user.name.split(' ')[0]}.` : 'Welcome to Launcher.'}
          </h1>
          <p style={{
            fontSize: '0.9375rem',
            color: 'var(--text-secondary)',
            letterSpacing: '-0.01em',
          }}>
            Run the 4-step pipeline on any startup idea — or jump to a specific stage.
          </p>
        </div>

        {/* Tools grid */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
          gap: 1,
          background: 'var(--border)',
          border: '1px solid var(--border)',
          borderRadius: 'var(--radius-lg)',
          overflow: 'hidden',
        }}>
          {tools.map((tool) => (
            <Link
              key={tool.to}
              to={tool.to}
              style={{
                textDecoration: 'none',
                background: 'var(--surface)',
                padding: '28px 24px',
                display: 'block',
                transition: 'background 150ms ease',
              }}
              onMouseEnter={e => e.currentTarget.style.background = 'var(--surface-2)'}
              onMouseLeave={e => e.currentTarget.style.background = 'var(--surface)'}
            >
              <div style={{
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between',
                marginBottom: 12,
              }}>
                <span style={{
                  fontSize: '0.9375rem',
                  fontWeight: 500,
                  color: 'var(--text-primary)',
                  letterSpacing: '-0.01em',
                }}>
                  {tool.label}
                </span>
                <span style={{
                  fontSize: '0.7rem',
                  fontWeight: 500,
                  letterSpacing: '0.08em',
                  textTransform: 'uppercase',
                  color: 'var(--text-tertiary)',
                }}>
                  {tool.tag}
                </span>
              </div>
              <p style={{
                fontSize: '0.875rem',
                color: 'var(--text-secondary)',
                lineHeight: 1.6,
                letterSpacing: '-0.01em',
              }}>
                {tool.desc}
              </p>
            </Link>
          ))}
        </div>

        {/* Pipeline note */}
        <div style={{
          marginTop: 40,
          padding: '20px 24px',
          background: 'var(--surface)',
          border: '1px solid var(--border)',
          borderRadius: 'var(--radius)',
          display: 'flex',
          alignItems: 'center',
          gap: 16,
        }}>
          <div style={{
            width: 6,
            height: 6,
            borderRadius: '50%',
            background: 'var(--text-tertiary)',
            flexShrink: 0,
          }} />
          <p style={{
            fontSize: '0.8125rem',
            color: 'var(--text-tertiary)',
            lineHeight: 1.6,
            letterSpacing: '-0.01em',
          }}>
            Each analysis is embedded into the RAG vector store. Future queries on similar ideas will benefit from your past results via cosine similarity retrieval.
          </p>
        </div>
      </div>
    </div>
  );
}
